gitalk:
  enable: true
  github_id: zxf4399
  repo: zxf4399.github.io
  client_id: eb16a06819b3c28d072a
  client_secret: e4a4d86e972b0f4b92827818e7fc85d2e3df968f
  admin_user: zxf4399
  distraction_free_mode: true
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token
  language: zh-CN
