baseURL: "http://example.org/"
languageCode: en-us
title: 郑贤锋的网络日志
theme: PaperMod

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20

params:
  EnableBusuanzi: true
  ShowReadingTime: true
  ShowWordCount: true
